local miner = require("miner")
local input = assert(io.open("distance.txt", "r"))
local distance = assert(tonumber(input:read("*a")))
input:close()
assert(distance >= 1 and distance <= 4 and distance % 1 == 0, "distance must be 1..4")
print("Mining " .. distance .. " blocks")
miner.tunnelAndReturn(distance)
local output = assert(io.open("report.txt", "w"))
output:write("Mined and returned: " .. distance .. "\n")
output:close()
print("Mining complete")
