local robot = require("robot")
local computer = require("computer")
local miner = require("miner")
local input = assert(io.open("distance.txt", "r"))
local distance = assert(tonumber(input:read("*a")))
input:close()
assert(distance >= 1 and distance <= 48 and distance % 1 == 0, "invalid distance")
local journal = assert(io.open("actions.tsv", "w"))
local function record(action, step, ok, reason)
  journal:write(action, "\t", tostring(step), "\t", tostring(ok), "\t", tostring(reason), "\t", tostring(computer.uptime()), "\t", tostring(computer.energy()), "\n")
  journal:flush()
end
miner.tunnelAndReturn(distance, record)
journal:close()
local report = assert(io.open("report.txt", "w"))
report:write("Mined and returned: ", tostring(distance), "\n")
report:close()
print("Cross-chunk mining complete: " .. distance)
